Add patch to move hexdump check to function that requires it
arekinath/triton-dehydrated pull request #66
Opened 2024-08-05 08:45 UTC by teutat3s

The `hexdump` binary is only required when using ZeroSSL as CA. This patch moves the check to the according function, unbreaking the script for Let's Encrypt CA.

Fixes #65. Tested script works on SmartOS with this change and Let's Encrypt as CA.

2024-08-05 13:03 UTC, danmcd approved these changes
1.) Make sure you get @bahamat 's signoff before pushing.

2.) I hope the dehydrated-io/dehydrated#910 suggestion of clever use of `od`(1) in a pipe will cure this permanently upstream.

2024-08-06 17:42 UTC, bahamat requested changes

2024-08-06 17:42 UTC, bahamat commented on PATCHES/000-fix-hexdump-check.patch
This is in the wrong place. Hexdump is used in EAB, not ZeroSSL.

2024-08-06 20:53 UTC, bahamat requested changes
Ok, I've sunk some time into this today. I have a proposed patch in dehydrated-io/dehydrated#943, so I'd prefer to use that instead.

You can pull that patch in here even if it doesn't land upstream.

2024-08-07 10:11 UTC, teutat3s commented
Done in https://github.com/TritonDataCenter/triton-dehydrated/commit/8303351c7185d5820bb4b9d45e7bcd663751f287.

2024-08-07 22:17 UTC, bahamat approved these changes

2024-08-07 22:18 UTC, merged